Repository DopplerShift13/DopplerShift, pull requests merged in 2025-05, with the labels that each got.

#526 more NT lore renaming and also synthroach fix, oops
  code/modules/mob/living/basic/vermin/cockroach.dm
  modular_doppler/modular_mobs/simple_animal/cockroach.dm
  modular_doppler/z_lore_rename.dm
Labels: Stale

#525 Uplink Bundle Subtype-ification & Uplink Edits
  modular_doppler/modular_uplink/code/ammunition.dm
  modular_doppler/modular_uplink/code/kit_special.dm
  modular_doppler/modular_uplink/code/kit_tactical.dm
  modular_doppler/modular_uplink/code/suits.dm
  modular_doppler/modular_uplink/code/uplink_kits.dm
  tgstation.dme
Labels: Stale

#527 Back at it Again
  _maps/map_files/Pubbystation/pubbystation.dmm
Labels: test-merge ready

#474 ports ss13 to the dragon engine (adds breacher knuckle)
  code/__DEFINES/~doppler_defines/powers.dm
  code/datums/martial/breacher_knuckle.dm
  code/game/objects/items/granters/martial_arts/breacher_knuckle.dm
  sound/items/weapons/breachknuckle/basicStrike.ogg
  sound/items/weapons/breachknuckle/doubleStrike.ogg
  sound/items/weapons/breachknuckle/longStrike.ogg
  sound/items/weapons/breachknuckle/shoveStrike.ogg
  tgstation.dme
Labels: test-merge ready, Stale

#543 Expands height scaling to SHORTEST and TALLEST and everything inbetween
  modular_doppler/height_scaling/code/preferences.dm
Labels: ready for merge

#540 [TEST-MERGE ONLY] Taurs
  code/__DEFINES/masks.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/~doppler_defines/bodyparts.dm
  code/__DEFINES/~doppler_defines/footsteps.dm
  code/__DEFINES/~doppler_defines/inventory.dm
  code/__DEFINES/~doppler_defines/item.dm
  code/__DEFINES/~doppler_defines/limbs.dm
  code/__DEFINES/~doppler_defines/mobs.dm
  code/__DEFINES/~doppler_defines/organ_slots.dm
  code/__DEFINES/~doppler_defines/species_clothing_paths.dm
  code/__DEFINES/~doppler_defines/vehicles.dm
  code/_globalvars/lists/objects.dm
  code/datums/bodypart_overlays/bodypart_overlay.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/elements/footstep.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/~doppler_earliest_defines.dm
  modular_doppler/accessable_storage/accessable_storage.dm
  modular_doppler/loadout_categories/categories/inhands.dm
  modular_doppler/modular_antagonists/sapper_gang/sapper_outfits.dm
  modular_doppler/modular_cosmetics/code/suits/basesuits.dm
  modular_doppler/modular_cosmetics/code/suits/misc.dm
  modular_doppler/modular_crafting/code/sheet_types.dm
  modular_doppler/modular_customization/preferences/taur.dm
  modular_doppler/modular_customization/tri_color/taur.dm
  modular_doppler/modular_species/_species.dm
  modular_doppler/modular_vending/code/tg_vendors/wardrobes.dm
  modular_doppler/taurs/code/bodyparts.dm
  modular_doppler/taurs/code/clothing.dm
  modular_doppler/taurs/code/taur_body.dm
  modular_doppler/taurs/code/taur_bodyparts.dm
  modular_doppler/taurs/code/taur_mechanics/constrict.dm
  modular_doppler/taurs/code/taur_mechanics/human.dm
  modular_doppler/taurs/code/taur_mechanics/item.dm
  modular_doppler/taurs/code/taur_mechanics/mod.dm
  modular_doppler/taurs/code/taur_mechanics/saddle_component.dm
  modular_doppler/taurs/code/taur_mechanics/saddles.dm
  modular_doppler/taurs/code/taur_mechanics/serpentine_taur.dm
  modular_doppler/taurs/code/taur_mechanics/taur_clothing_offset.dm
  modular_doppler/taurs/code/taur_sprites/suits.dm
  modular_doppler/taurs/code/taur_types.dm
  modular_doppler/taurs/icons/suit_taur_hoof.dmi
  modular_doppler/taurs/icons/suit_taur_paw.dmi
  modular_doppler/taurs/icons/suit_taur_snake.dmi
  modular_doppler/taurs/icons/taur.dmi
  modular_doppler/taurs/icons/taur_invisible_legs.dmi
  modular_doppler/taurs/icons/taur_masking_helpers.dmi
  modular_doppler/taurs/icons/taur_mechanics/ability.dmi
  modular_doppler/taurs/icons/taur_mechanics/saddles.dmi
  modular_doppler/taurs/icons/taur_mechanics/tail.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/parts_color.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/parts_taur.tsx
Labels: test-merge ready

#546 Disrupts The Doppler Fit Game Once More
  modular_doppler/loadout_categories/categories/accessories.dm
  modular_doppler/loadout_categories/categories/backpacks.dm
  modular_doppler/loadout_categories/categories/clothing.dm
  modular_doppler/loadout_categories/categories/glasses.dm
  modular_doppler/loadout_categories/categories/gloves.dm
  modular_doppler/loadout_categories/categories/heads.dm
  modular_doppler/loadout_categories/categories/neck.dm
  modular_doppler/loadout_categories/categories/shoes.dm
  modular_doppler/loadout_categories/categories/undersuit.dm
  modular_doppler/species_clothes/code/coalition/armor.dm
  modular_doppler/species_clothes/code/coalition/clothing.dm
  modular_doppler/species_clothes/code/coalition/storage.dm
  modular_doppler/species_clothes/code/tiziria/armor.dm
  modular_doppler/species_clothes/code/tiziria/clothing.dm
  modular_doppler/species_clothes/code/tiziria/storage.dm
  modular_doppler/species_clothes/icons/generic/lefthand.dmi
  modular_doppler/species_clothes/icons/generic/righthand.dmi
  modular_doppler/species_clothes/icons/tajara/gear.dmi
  modular_doppler/species_clothes/icons/tajara/gear_worn.dmi
  modular_doppler/species_clothes/icons/tajara/gear_worn_dig.dmi
  modular_doppler/species_clothes/icons/tiziria/gear.dmi
  modular_doppler/species_clothes/icons/tiziria/gear_worn.dmi
  modular_doppler/species_clothes/icons/tiziria/gear_worn_dig.dmi
  modular_doppler/species_clothes/icons/vulp/gear.dmi
  modular_doppler/species_clothes/icons/vulp/gear_worn.dmi
  modular_doppler/species_clothes/icons/vulp/gear_worn_dig.dmi
  tgstation.dme
Labels: test-merge ready

#553 Restore detective brown/noir trenchcoat/blazer loadout items
  modular_doppler/loadout_categories/categories/clothing.dm
Labels: ready for merge

#555 Fixes missing labcoat sprites
  modular_doppler/modular_cosmetics/icons/mob/suit/labcoat.dmi
Labels: ready for merge

#559 (Fullmerge Me At Your Own Peril) Obliv- Colony Junk Remaster
  _maps/map_files/Pubbystation/pubbystation.dmm
  _maps/shuttles/~doppler_shuttles/diy_diy_large.dmm
  _maps/shuttles/~doppler_shuttles/mining_cigale.dmm
  _maps/shuttles/~doppler_shuttles/outbound_expedition.dmm
  _maps/shuttles/~doppler_shuttles/pirate_sapper.dmm
  modular_doppler/colony_fabricator/code/appliances/chem_machines.dm
  modular_doppler/colony_fabricator/code/appliances/co2_cracker.dm
  modular_doppler/colony_fabricator/code/appliances/foodricator.dm
  modular_doppler/colony_fabricator/code/appliances/kitchen_appliances/griddle.dm
  modular_doppler/colony_fabricator/code/appliances/kitchen_appliances/macrowave.dm
  modular_doppler/colony_fabricator/code/appliances/kitchen_appliances/range.dm
  modular_doppler/colony_fabricator/code/appliances/recycler.dm
  modular_doppler/colony_fabricator/code/appliances/wind_turbine.dm
  modular_doppler/colony_fabricator/code/colony_fabricator.dm
  modular_doppler/colony_fabricator/code/design_datums/fabricator_flag_additions/construction.dm
  modular_doppler/colony_fabricator/code/design_datums/fabricator_flag_additions/machine_boards.dm
  modular_doppler/colony_fabricator/code/design_datums/fabricator_flag_additions/tools.dm
  modular_doppler/colony_fabricator/code/design_datums/flatpack_machines.dm
  modular_doppler/colony_fabricator/code/design_datums/tools.dm
  modular_doppler/colony_fabricator/code/machines/arc_furnace.dm
  modular_doppler/colony_fabricator/code/machines/ore_silo.dm
  modular_doppler/colony_fabricator/code/machines/power_storage_unit.dm
  modular_doppler/colony_fabricator/code/machines/rtg.dm
  modular_doppler/colony_fabricator/code/machines/solar_panels.dm
  modular_doppler/colony_fabricator/code/machines/solid_fuel_generator.dm
  modular_doppler/colony_fabricator/code/machines/stirling_generator.dm
  modular_doppler/colony_fabricator/code/machines/thermomachine.dm
  modular_doppler/colony_fabricator/code/repacking_element.dm
  modular_doppler/colony_fabricator/code/tools/tools.dm
  modular_doppler/colony_fabricator/icons/cell_charger.dmi
  modular_doppler/colony_fabricator/icons/kitchen_stuff/griddle.dmi
  modular_doppler/colony_fabricator/icons/kitchen_stuff/microwave.dmi
  modular_doppler/colony_fabricator/icons/kitchen_stuff/range.dmi
  modular_doppler/colony_fabricator/icons/machines.dmi
  modular_doppler/colony_fabricator/icons/ore_silo.dmi
  modular_doppler/colony_fabricator/icons/packed_machines.dmi
  modular_doppler/colony_fabricator/icons/power_storage_unit/large_battery.dmi
  modular_doppler/colony_fabricator/icons/power_storage_unit/small_battery.dmi
  modular_doppler/colony_fabricator/icons/stirling_generator/big_generator.dmi
  modular_doppler/colony_fabricator/icons/stirling_generator/packed_machines.dmi
  modular_doppler/damage_control/code/emergency_fab.dm
  modular_doppler/epic_loot/code/random_spawners_real.dm
  modular_doppler/kahraman_equipment/code/gps_beacon.dm
  modular_doppler/kahraman_equipment/code/ore_thumper.dm
  modular_doppler/modular_antagonists/sapper_gang/sapper_outfits.dm
  tgstation.dme
Labels: ready for merge

#550 Few antag cantina additions/improvements
  _maps/doppler/cantina/badguyzone.dmm
  modular_doppler/modular_antagonists/cantina/cantina_items.dm
  tgstation.dme
Labels: ready for merge

#557 Added two Megafauna Ruins to Truth, featuring the BDM and the Hierophant
  _maps/RandomRuins/IceRuins/doppler/icemoon_underground_blooddrunk1.dmm
  _maps/RandomRuins/IceRuins/doppler/icemoon_underground_blooddrunk2.dmm
  _maps/RandomRuins/IceRuins/doppler/icemoon_underground_hierophant.dmm
  modular_doppler/modular_mapping/code/ruins/icemoon.dm
Labels: test-merge ready

#573 Accessory button fix
  code/modules/client/preferences/species_features/lizard.dm
  code/modules/client/preferences/species_features/moth.dm
  modular_doppler/modular_customization/preferences/body_marking_lizard.dm
  modular_doppler/modular_customization/preferences/ears.dm
  modular_doppler/modular_customization/preferences/frills.dm
  modular_doppler/modular_customization/preferences/horns.dm
  modular_doppler/modular_customization/preferences/snout.dm
  modular_doppler/modular_customization/preferences/tail.dm
  modular_doppler/modular_customization/preferences/taur.dm
  modular_doppler/modular_customization/preferences/wings.dm
Labels: ready for merge

#587 Doppler Bat DLC
  code/__DEFINES/~doppler_defines/mutant_variations.dm
  modular_doppler/modular_customization/accessories/code/non_species_specific/avian_accessories/avian_tail.dm
  modular_doppler/modular_customization/accessories/code/non_species_specific/avian_accessories/avian_wings.dm
  modular_doppler/modular_customization/accessories/icons/non_species_specific/avian/avian_tail.dmi
  modular_doppler/modular_customization/accessories/icons/non_species_specific/avian/avian_wings.dmi
  modular_doppler/modular_customization/organs/code/tail.dm
  modular_doppler/modular_customization/preferences/species_traits.dm
  modular_doppler/modular_species/_species.dm
  modular_doppler/modular_species/species_types/genemod/genemod.dm
Labels: test-merge ready

#586 Look at me Hacker (Temp. Flavor text fix for Ai and Cyborgs)
  code/game/machinery/hologram.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
Labels: test-merge ready

#590 Adds robot drinks and some other racial drinks
  modular_doppler/modular_food_drinks_and_chems/food_and_drinks/drinks_recipes.dm
Labels: test-merge ready

#597 Adds screen-tip for accessable storage items/organs
  code/modules/mob/living/carbon/carbon_context.dm
Labels: ready for merge

#601 fixes that really annoying shuttle powernet bug in a probably really bad way
  modular_doppler/shuttle_gear/code/wirefix.dm
  tgstation.dme
Labels: test-merge ready

#596 [TEST-MERGE FIRST] [BOUNTY] Adds the Registered Prescription Quirk
  modular_doppler/prescription_quirk/prescription_quirk.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/doppler/prescription.tsx
Labels: test-merge ready
