Repository DopplerShift13/DopplerShift, pull requests merged in 2025-07, with the labels that each got.

#623 Adding more customization to plantpeople
  code/modules/client/preferences/species_features/pod.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_pod.png
  code/~doppler_earliest_defines.dm
  config/game_options.txt
  modular_doppler/modular_customization/bodypart/bodypart_overrides.dm
  modular_doppler/modular_customization/organs/code/eyes.dm
Labels: ready for merge

#556 The Mad Dog's Style & Friends
  code/__DEFINES/~doppler_defines/powers.dm
  code/__DEFINES/~doppler_defines/sources.dm
  modular_doppler/martial_arts/granters.dm
  modular_doppler/martial_arts/mad_dog.dm
  modular_doppler/modular_uplink/code/stealthy.dm
  tgstation.dme
Labels: Stale, ready for merge

#588 Adds partial language integration for our language menu
  code/__DEFINES/~doppler_defines/language.dm
  code/modules/client/preferences_savefile.dm
  modular_doppler/languages/code/language menu/client_languages.dm
  modular_doppler/languages/code/language menu/language_holder.dm
  modular_doppler/modular_customization/preferences/preferences.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/LanguagesMenu.tsx
Labels: test-merge ready

#638 Allow borgs to move pulled objects, place pulled items on tables/racks, and flip tables for fun
  modular_doppler/modular_silicons/move_pulled/attack_robot_overrides.dm
  modular_doppler/modular_silicons/table_interactions/table_overrides.dm
  tgstation.dme
Labels: test-merge ready
