Repository DopplerShift13/DopplerShift, pull requests merged in 2025-09, with the labels that each got.

#706 finally lets doppler characters have a rack
  modular_doppler/modular_cosmetics/GAGS/greyscale_configs_objects.dm
  modular_doppler/modular_crafting/code/sheet_types.dm
  modular_doppler/modular_items/code/aac_device.dm
  modular_doppler/modular_items/code/bettermed_overrides.dm
  modular_doppler/modular_items/code/car_battery.dm
  modular_doppler/modular_items/code/coffeeholder.dm
  modular_doppler/modular_items/code/conversion_kits.dm
  modular_doppler/modular_items/code/drinks.dm
  modular_doppler/modular_items/code/emergency_breach_equipment.dm
  modular_doppler/modular_items/code/hairbrush.dm
  modular_doppler/modular_items/code/invisible_gear.dm
  modular_doppler/modular_items/code/pda_reskins.dm
  modular_doppler/modular_items/code/shelf.dm
  modular_doppler/modular_items/code/shipchem_overrides.dm
  modular_doppler/modular_items/code/signature_beacon.dm
  modular_doppler/modular_items/code/summon_beacon.dm
  modular_doppler/modular_items/icons/hairbrush.dmi
  modular_doppler/modular_items/icons/inhand_left.dmi
  modular_doppler/modular_items/icons/inhand_right.dmi
  modular_doppler/modular_items/icons/pda_icons.dmi
  modular_doppler/modular_items/icons/rack.dmi
  tgstation.dme
Labels: Sprites, Feature

#722 Reorganize the loadout, part 1: Glasses
  code/modules/loadout/categories/glasses.dm
  modular_doppler/loadout_categories/categories/glasses.dm
Labels: Quality of Life, Fix, Feature

#721 miniports planetary samples to cargo
  modular_doppler/modular_cargo/doppler_cargo_packs.dm
Labels: Feature

#725 I have no mouth but I will scream
  modular_doppler/modular_species/species_types/android/android.dm
Labels: Feature

#700 Adds a 'Limping' quirk for all your old man hip problem needs
  code/__DEFINES/~doppler_defines/quirks.dm
  code/_globalvars/~doppler_globalvars/lists/quirks.dm
  code/datums/status_effects/wound_effects.dm
  modular_doppler/modular_quirks/limping/limping.dm
  modular_doppler/modular_quirks/limping/preferences.dm
  modular_doppler/modular_weapons/code/captain_signature_weapon/options/sabres.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/dopplershift_preferences/limping.tsx
Labels: Stale, UI, Fix, Feature

#712 Disables station traits: Intern Voice & GMM Spotlight
  modular_doppler/lore/overrides/station_traits/neutral_traits.dm
Labels: Removal

#727 Makes the command bodyguard's skillchip spawn in their backpack
  modular_doppler/modular_jobs/command_bodyguard/code/command_bodyguard.dm
Labels: Quality of Life

#723 Pizza bomb changes
  code/modules/uplink/uplink_items/explosive.dm
  code/modules/uplink/uplink_items/nukeops.dm
  modular_doppler/modular_uplink/code/smallerpizzabomb.dm
  tgstation.dme
Labels: Balance

#729 Adds the Civilian Modsuit to the Backpack Loadout Category
  modular_doppler/loadout_categories/categories/backpacks.dm
Labels: ready for merge, Feature

#735 Fixes a random severity for the limping quirk runtiming.
  modular_doppler/modular_quirks/limping/limping.dm
Labels: Fix

#734 makes loincloths not be tailored by resonant psychopaths and instead be at the same height regardless of which direction you are facing
  modular_doppler/hearthkin/primitive_genemod/icons/loincloth.dmi
  modular_doppler/modular_customization/accessories/icons/underwear/underwear.dmi
Labels: SPEEDMERGE ⚡, Sprites
