Repository DopplerShift13/DopplerShift, pull requests merged in 2025-02, with the labels that each got.

#393 Bypasses the whole* Techweb (puts it all in a modular file)
  modular_doppler/research/techweb/roundstart_techweb_nodes.dm
  tgstation.dme
Labels: ready for merge

#395 Pubby, Doppler-style [Please Testmerge only]
  _maps/_basemap.dm
  _maps/map_files/Pubbystation/pubbystation.dmm
  _maps/pubbystation.json
  config/maps.txt
Labels: test-merge ready, do not merge

#398 Slight Slime Nerfs To Make Them Actually Work As Intended
  modular_doppler/modular_species/species_types/slimes/code/roundstartslimes.dm
Labels: Stale

#392 A Few More Loadout Items
  modular_doppler/loadout_categories/categories/glasses.dm
  modular_doppler/loadout_categories/categories/masks.dm
  modular_doppler/modular_cosmetics/code/face/glasses.dm
  modular_doppler/modular_cosmetics/code/face/masks.dm
  modular_doppler/modular_cosmetics/icons/mob/face/masks.dmi
  modular_doppler/modular_cosmetics/icons/obj/face/masks.dmi
Labels: Stale
